project:
  type: book
  output-dir: docs
  
book:
  title: "🐍 Python Intro"
  author: "Francisco Alfaro Medina"
  date: "07/01/2024"
  favicon: "images/icon.png"
  repo-url: "https://github.com/fralfaro/python_intro2"


  chapters:
    - index.qmd
    - part: prefacio/intro.qmd
      chapters:
        - prefacio/01_intro_progra.qmd
        - prefacio/02_intro_python.qmd
    - part: contenidos/intro.qmd
      chapters:
        - contenidos/03_nomenclatura.qmd
        - contenidos/04_control_flujo.qmd
        - contenidos/05_estructura_datos.qmd
        - contenidos/06_funciones.qmd
        - contenidos/07_excepciones.qmd
        - contenidos/08_buenas_practicas.qmd
        - contenidos/09_solucion.qmd



lang: es

format:
  html:
    smooth-scroll: true
    theme:
      light: [flatly, stylesheets/custom2.scss]
      dark: [flatly, stylesheets/custom2.scss, stylesheets/theme-dark.scss]
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true
    epub:
      cover-image: images/cover.png

editor: visual

execute:
  freeze: true

filters: 
  - pyodide